### ISSUE TITLE
能否打开App的时候不显示？等我点击按钮后再显示日历视图，与RecyclerView联动

### ISSUE THREAD

**Issue by sendtion** [huanghaibin-dev/CalendarView#121]
如题。
我想在打开app的时候是不显示日历视图的，用户可以通过按钮来显示和隐藏
我直接setVisibility发现有问题。请问有什么好的解决方式吗？

**Comment by hbzkw** [comment]
![qq 20180423164203](https://user-images.githubusercontent.com/10335430/39115764-4a1a466e-4715-11e8-9665-4b456e942e38.png)

将Xml com.haibin.calendarview.CalendarLayout 下的app:default_status="shrink" 改为shrink就可以如上图，前提是你下面的布局足够铺满屏幕

**Comment by sendtion** [comment]
@hbzkw 您误解我的意思了。我说的不是收缩视图，而是隐藏。你说的使用app:default_status="shrink"是收缩视图默认显示周视图，我要的是默认不显示周视图也不显示月视图，用户点击按钮才显示和隐藏这个视图。这个可以实现吗？

**Comment by sendtion** [comment]
@hbzkw 谢谢！我知道怎么搞了，只用你的CalendarView就可以了。有点遗憾的是不能切换周视图和月视图了

**Comment by hbzkw** [comment]
设置view的visible属性发自坚果 Pro 2
* body { padding:0 16px 30px !important; margin:0 !important;background-color: #ffffff; line-height: 1.4;word-wrap: break-word; word-break: normal; } div {word-wrap: break-word; word-break: normal; } p {word-wrap: break-word; word-break: normal; text-indent: 0pt !important; } span {word-wrap: break-word; word-break: normal; } a {word-wrap: break-word; word-break: normal; } td {word-wrap: break-word; word-break: break-all; }Sendtion <notifications@github.com>
于 2018年4月23日 下午9:26写道：@hbzkw 您误解我的意思了。我说的不是收缩视图，而是隐藏。你说的使用app:default_status="shrink"是收缩视图默认显示周视图，我要的是默认不显示周视图也不显示月视图，用户点击按钮才显示和隐藏这个视图。这个可以实现吗？

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/huanghaibin-dev/CalendarView","title":"huanghaibin-dev/CalendarView","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/huanghaibin-dev/CalendarView"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sendtion in #121: @hbzkw 您误解我的意思了。我说的不是收缩视图，而是隐藏。你说的使用app:default_status=\"shrink\"是收缩视图默认显示周视图，我要的是默认不显示周视图也不显示月视图，用户点击按钮才显示和隐藏这个视图。这个可以实现吗？"}],"action":{"name":"View Issue","url":"https://github.com/huanghaibin-dev/CalendarView/issues/121#issuecomment-383574469"}}}

**Comment by gexiangjie** [comment]
我也正好需要这个需求 但是我还要月视图 不只是周视图 该怎么搞呢

**Comment by sendtion** [comment]
> 我也正好需要这个需求 但是我还要月视图 不只是周视图 该怎么搞呢

我只用了月视图，否则会布局错乱
