### ISSUE TITLE
ViewPager 的问题

### ISSUE THREAD

**Issue by yccheok** [huanghaibin-dev/CalendarView#235]
您好。

我现在把 CalendarView 装在 ViewPager 里

```
<com.haibin.calendarview.CalendarLayout>
    <ScrollView>
        <com.haibin.calendarview.CalendarView>
        </com.haibin.calendarview.CalendarView>
    </ScrollView>
</com.haibin.calendarview.CalendarLayout>
```

我也用了
```

                app:month_view_scrollable="false"
                app:week_view_scrollable="false"
                app:year_view_scrollable="false"
```
![screenshot_20180918-040433](https://user-images.githubusercontent.com/308276/45647535-b0765180-baf8-11e8-8ffc-13760bea0355.png)

当我触摸日历 左Swipe 或 右Swipe，我想转换到 “全部” 或 “生活” tab。现在的现象是，左Swipe 或 右Swipe 没有反应。

我知道在日历库里，有一个 MonthViewPager。不知是不是因为我的应用有了自家的 ViewPager，然后自家的 ViewPager 里有个 MonthViewPager，就会产生这样的问题？

谢谢。

**Comment by yccheok** [comment]
如果您想体验这问题，欢迎下载尝试 https://wenote.jstock.co

万分感激。

**Comment by yccheok** [comment]
嗨，我用以下的方案解决我面对的问题。（我也不十分确定这解决方案的正确性）不知您有兴趣merge进master吗？

https://github.com/yccheok/CalendarView/commit/0f2a54397cc30afcbb6cdf0473d906ef27f60243

**Comment by huanghaibin-dev** [comment]
这种滑动冲突不能这么解决的，外层的ViewPager嵌套了日历ViewPager导致事件冲突，这应该去解决外层ViewPager的事件拦截和分发，而不是去修改日历本身，你只需要简简单单去对外层ViewPager重写事件拦截方法就可以了发自我的iPhone------------------ 原始邮件 ------------------发件人: Yan Cheng Cheok  <notifications@github.com>发送时间: 2018年9月18日 20:06收件人: huanghaibin-dev/CalendarView <CalendarView@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[huanghaibin-dev/CalendarView] ViewPager 的问题 (#235)嗨，我用以下的方案解决我面对的问题。（我也不十分确定这解决方案的正确性）不知您有兴趣merge进master吗？
yccheok@0f2a543

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/huanghaibin-dev/CalendarView","title":"huanghaibin-dev/CalendarView","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/huanghaibin-dev/CalendarView"}},"updates":{"snippets":[{"icon":"PERSON","message":"@yccheok in #235: 嗨，我用以下的方案解决我面对的问题。（我也不十分确定这解决方案的正确性）不知您有兴趣merge进master吗？\r\n\r\nhttps://github.com/yccheok/CalendarView/commit/0f2a54397cc30afcbb6cdf0473d906ef27f60243"}],"action":{"name":"View Issue","url":"https://github.com/huanghaibin-dev/CalendarView/issues/235#issuecomment-422366361"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/huanghaibin-dev/CalendarView/issues/235#issuecomment-422366361",
"url": "https://github.com/huanghaibin-dev/CalendarView/issues/235#issuecomment-422366361",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [huanghaibin-dev/CalendarView] ViewPager 的问题 (#235)",
"sections": [
{
"text": "",
"activityTitle": "**Yan Cheng Cheok**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@yccheok",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"huanghaibin-dev/CalendarView\",\n\"issueId\": 235,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"huanghaibin-dev/CalendarView\",\n\"issueId\": 235\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/huanghaibin-dev/CalendarView/issues/235#issuecomment-422366361"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 380798554\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by yccheok** [comment]
可是，要如何修改外层的 ViewPager? 因为，内层的 ViewPager 会首先吃掉 Event，外层的 ViewPager 没机会接收到 Event。

**Comment by huanghaibin-dev** [comment]
重写外层的onInterceptTouchEvent，事件会先经过外层的ViewPager，这里可以按条件返回true，表示拦截，这样ChildView就无法接收事件了，这里很简单，你只需要判断当前是日历项，则继续判断最外层的事件x坐标，如果x<临界值假如100，可以swipeToNext，则return true，如果x>width-100，则可以swipeToPre，return true，再这两个范围之内的，则return super，让日历去处理即可

**Comment by yccheok** [comment]
谢谢。会照着这思路尝试看。

黄海彬 <notifications@github.com> 於 2018年9月18日 週二 下午10:41 寫道：
