### ISSUE TITLE
请问标记右上角需要设置图片，需要怎么写呢

### ISSUE THREAD

**Issue by 1226362423** [huanghaibin-dev/CalendarView#457]
![image](https://user-images.githubusercontent.com/15227754/56720522-a050df80-6775-11e9-83c3-a9dced92ee91.png)

**Comment by 1226362423** [comment]
类似上图这种

**Comment by huanghaibin-dev** [comment]
drawBitmap，需要稍微了解以下Rect的相关操作缩放到适合的大小即可

**Comment by 1226362423** [comment]
@huanghaibin-dev   好的谢谢了 正在解决中 ^_^，  还有个小问题要问下 ，范围选择了之后，还需要在范围选择区域进行单选某天，范围选择效果还是在的  这个需要怎么做呢，如第一楼的图，谢谢大神了

**Comment by huanghaibin-dev** [comment]
你这种不适合范围选择，建议改用多项模式，范围选择跟你这个是冲突的

发自我的 iPhone

**Comment by 1226362423** [comment]
@huanghaibin-dev  谢谢回复，您是说的多项模式还是多选？  还有 我刚刚也试了下范围选择 多个段落，范围选择好像是不能同时选择多个段的，产品大大的需求是可以选择多段，类似图一，由两个不同开始时间，结束时间选择的不同的范围， 范围选择这个好像就不满足需求了 怎么解决这个问题比较好呢^_^

**Comment by huanghaibin-dev** [comment]
多选模式，你这种多个范围的只能改源码了，暂时无解

发自我的 iPhone

**Comment by 1226362423** [comment]
@huanghaibin-dev  可不可以在不改源码的情况下，用标记多个日期的形式，在onDrawScheme中做判断实现这种效果吗？然后拿到标记的时间段？

**Comment by huanghaibin-dev** [comment]
很麻烦等，理论上可以这样做发自我的iPhone------------------ 原始邮件 ------------------发件人: caoBanJin  <notifications@github.com>发送时间: 2019年4月27日 10:23收件人: huanghaibin-dev/CalendarView <CalendarView@noreply.github.com>抄送: 黄海彬 <huanghaibin_dev@163.com>, Mention <mention@noreply.github.com>主题: 回复：[huanghaibin-dev/CalendarView] 请问标记右上角需要设置图片，需要怎么写呢 (#457)@huanghaibin-dev  可不可以在不改源码的情况下，用标记多个日期的形式，在onDrawScheme中做判断实现这种效果吗？然后拿到标记的时间段？

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/huanghaibin-dev/CalendarView","title":"huanghaibin-dev/CalendarView","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/huanghaibin-dev/CalendarView"}},"updates":{"snippets":[{"icon":"PERSON","message":"@1226362423 in #457: @huanghaibin-dev  可不可以在不改源码的情况下，用标记多个日期的形式，在onDrawScheme中做判断实现这种效果吗？然后拿到标记的时间段？\r\n"}],"action":{"name":"View Issue","url":"https://github.com/huanghaibin-dev/CalendarView/issues/457#issuecomment-487247124"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/huanghaibin-dev/CalendarView/issues/457#issuecomment-487247124",
"url": "https://github.com/huanghaibin-dev/CalendarView/issues/457#issuecomment-487247124",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by 1226362423** [comment]
![image](https://user-images.githubusercontent.com/15227754/57187173-eea47200-6f1d-11e9-9e7e-9dbe08e6fcfb.png)

目前已经做出来这种图  都是标记出来的  不是多选
