### ISSUE TITLE
请问有没有办法加scrollToTomorrow() 和 scrollToYesterday()

### ISSUE THREAD

**Issue by ohpoloha** [huanghaibin-dev/CalendarView#76]
这主要是用来在下方塞viewpager左右滑动的时候可以连带上面的CalendarView一起更新, 所以需要昨天和明天

我目前自己用下面的方法大概实现了
```
val tmr = Calendar.getInstance()
tmr.set(selectedCalendar.year, selectedCalendar.month - 1, selectedCalendar.day)
tmr.add(Calendar.DATE, 1)
scrollToCalendar(tmr.get(Calendar.YEAR), tmr.get(Calendar.MONTH) + 1, tmr.get(Calendar.DAY_OF_MONTH))
```

可是有个问题, 由于大部分情况下viewpager滑动的时候都是显示周历, 在每个月的交替, 比如今年的2月28是礼拜三, 所以在周历上还会存在着同个礼拜的3/1-3/3, 导致一路滑到3/3都没问题, 滑到3/4的时候会呼叫OnMonthChangeListener进而把当前月份设定到了3/1, 所以在这当下的现在日期就变成3/1, 而在使用者看到的就会变成3/2->3/3->3/4->3/2->3/3->3/4->3/5

虽然监听OnMonthChangeListener再把日期换回去或许就解决了(我还没试), 但是感觉这样做有些hacky
此方法在显示月曆的情况下是没有问题的
感激不尽

**Comment by huanghaibin-dev** [comment]
暂时没有提供这两个方法，我后续提供一下吧

**Comment by ohpoloha** [comment]
非常感谢您!

**Comment by ohpoloha** [comment]
@huanghaibin-dev 
你好, 我后来想了一下, 觉得我的实现方法不该有问题, 虽然有点hacky, 所以我做了一下实验
```
Log.d(TAG, calendarView.selectedCalendar.toString())

Handler().postDelayed({
    calendarView.scrollToCalendar(2018, 5, 25)
    Log.d(TAG, calendarView.selectedCalendar.toString())
}, 1000)
```
发现我的假设是正确的, 这个比较像是一个bug, 因为第一次会打印出今天的日期, 第二次因为不是当前月份, 所以设定完之后触发了由于月份更改而把日期设为一号的特性, 所以第二次打印就出现了`20180501`, 而不是`20180525`

**Comment by huanghaibin-dev** [comment]
@ohpoloha 修复了，但是没有添加其它方法

**Comment by ohpoloha** [comment]
@huanghaibin-dev 
谢谢您! 我试了一下效果很棒 但是发现还有两个小问题
就是假设以今天2/9/2018来看, 如果呼叫`scrollToCalendar`到三月的第二个以后的礼拜天, 例如`calendarView.scrollToCalendar(2018, 3, 11)`, 在周历的显示状态下, 会显示3/4-3/10这一週, 可是除了礼拜天以外的其他日期都可以正常显示并且highlight

再来就是我发现`scrollToCalendar`在新版裡面并不会呼叫`OnDateSelectedListener`, 不知道这是不是故意拿掉而避免月曆的第一天被选取的特性? 这导致令一个问题发生, 就是假设呼叫`scrollToCalendar(2018, 3, 12)`, 在周历的显示下礼拜一正常被选取, 可是拉开到月曆的时候却变成3/1/2018被选取了

非常感谢您提供这个好用的开源库!!

**Comment by ohpoloha** [comment]
@huanghaibin-dev 
您好, 多测试了一下发现还是有些其他问题
例如今天是2/9/2018 然后

calendarView.scrollToCalendar(2018, 2,14)
Log.d(TAG, calendarView.selectedCalendar.toString())

Handler().postDelayed({
    calendarView.scrollToCalendar(2018, 2,7)
    Log.d(TAG, calendarView.selectedCalendar.toString())
}, 1000)

会打印出20180214然后20180209, 但是一秒后打印出的应该是20180207才对

再来同样是以2/9/2018开始
calendarView.scrollToCalendar(2018, 3,12)
Log.d(TAG, calendarView.selectedCalendar.toString())

Handler().postDelayed({
    calendarView.scrollToCalendar(2018, 3,11)
    Log.d(TAG, calendarView.selectedCalendar.toString())
}, 1000)

这个就是打印出20180312然后20180304
以上情况都是在周历上操作的时候发生的

谢谢

**Comment by huanghaibin-dev** [comment]
@ohpoloha 已经OK了，不好意思

**Comment by ohpoloha** [comment]
@huanghaibin-dev 
太感谢您了!
还有最后一个小问题, 就是一样以今天2/10/2018开始, 呼叫`calendarView.scrollToCalendar() `到三月的第二个礼拜天之后的礼拜天都会造成显示错误, 是只有礼拜天会有这种情况出现, 就好比呼叫`calendarView.scrollToCalendar(2018,3,18)`, 週曆会出现在3/11-3/17的那一週, 往回也是如此, 例如

```
Handler().postDelayed({
    calendarView.scrollToCalendar(2018,3,19)
    Log.d(TAG, calendarView.selectedCalendar.toString())

    Handler().postDelayed({
        calendarView.scrollToCalendar(2018,3,18)
        Log.d(TAG, calendarView.selectedCalendar.toString())
    },1000)
},1000)
```

3/19的那週正常显示, 但是3/18的週曆会出现3/11-3/17 的那週
以上在月曆的部分都没问题
谢谢

**Comment by huanghaibin-dev** [comment]
@ohpoloha 已经修复了的，你更新代码看看，这个都正常了

**Comment by huanghaibin-dev** [comment]
@ohpoloha 怎么触发的？我这里很正常啊

**Comment by ohpoloha** [comment]
@huanghaibin-dev 
您好, 其实只要呼叫`calendarView.scrollToCalendar(2018,3,18)`, 就会发现週曆显示的问题
我上面放两个日期只是为了查看第一次呼叫到3/19是正常的
我有拍了一小段视频, 可以看到今天是2/11/2018, 然后呼叫`calendarView.scrollToCalendar(2018,3,18)`之后, 週曆显示是3/11-3/18这週, 但是打印出来的确实是`20180318`, 如果此时拉开成月曆的话也可以看到3/18被选取, 所以其实问题只有在显示的週曆上

![ezgif com-video-to-gif 2](https://user-images.githubusercontent.com/2823640/36079011-1dcdd450-0f33-11e8-9b3a-d391d7e1b4d1.gif)

**Comment by ohpoloha** [comment]
@huanghaibin-dev 
这个视频可能更清楚些

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/2823640/36079224-d21c6078-0f35-11e8-98b0-618f04437492.gif)

**Comment by ohpoloha** [comment]
@huanghaibin-dev  您好, 我后来发现其实只要选今天开始四个礼拜后的星期天, 然后做週月曆切换就可以複现了
![ezgif com-video-to-gif 2](https://user-images.githubusercontent.com/2823640/36080665-ecd6c70c-0f47-11e8-92d4-9717b5e85eac.gif)

**Comment by huanghaibin-dev** [comment]
你试试clone master的代码看看，有没有这个问题，貌似3.2.3是存在这个，但是新版本是解决了的发自我的iPhone------------------ 原始邮件 ------------------发件人: bruce chen  <notifications@github.com>发送时间: 2018年2月12日 08:25收件人: huanghaibin-dev/CalendarView <CalendarView@noreply.github.com>抄送: 黄海彬 <huanghaibin_dev@163.com>, Mention <mention@noreply.github.com>主题: 回复：[huanghaibin-dev/CalendarView] 请问有没有办法加scrollToTomorrow() 和 scrollToYesterday() (#76)@huanghaibin-dev  您好, 我后来发现其实只要选今天开始四个礼拜后的星期天, 然后做週月曆切换就可以複现了


—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/huanghaibin-dev/CalendarView","title":"huanghaibin-dev/CalendarView","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/huanghaibin-dev/CalendarView"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ohpoloha in #76: @huanghaibin-dev  您好, 我后来发现其实只要选今天开始四个礼拜后的星期天, 然后做週月曆切换就可以複现了\r\n![ezgif com-video-to-gif 2](https://user-images.githubusercontent.com/2823640/36080665-ecd6c70c-0f47-11e8-92d4-9717b5e85eac.gif)\r\n"}],"action":{"name":"View Issue","url":"https://github.com/huanghaibin-dev/CalendarView/issues/76#issuecomment-364805212"}}}

**Comment by ohpoloha** [comment]
您好
我尝试clone之后用你的例子在我机器上跑, 也是有一样的问题
然后我还有试着把版本换到3.2.3发现上面最早提到的问题还存在, 换成3.2.4之后就只剩下最后那个礼拜天的问题, 所以代表我确实是使用3.2.4, 不然其他问题也不会修復了

我另外写了一个测试的例子在这, 麻烦你有空可否帮我看看是哪裡用错了, 谢谢你
[CalendarViewTest.zip](https://github.com/huanghaibin-dev/CalendarView/files/1715422/CalendarViewTest.zip)

![ezgif com-video-to-gif 4](https://user-images.githubusercontent.com/2823640/36085210-e64063ea-0f78-11e8-9cce-29b0f4f5ad60.gif)

**Comment by huanghaibin-dev** [comment]
@ohpoloha 稍等一下，我下载来看看

**Comment by huanghaibin-dev** [comment]
@ohpoloha 你好，可以加一下我的QQ：1505651581，方便交流一下

**Comment by ohpoloha** [comment]
@huanghaibin-dev 
加了, 谢谢

**Comment by ohpoloha** [comment]
@huanghaibin-dev 你好, 请问有收到我的ＱＱ邀请吗

**Comment by huanghaibin-dev** [comment]
没有收到邀请，1505651581

发自我的 iPhone

**Comment by ohpoloha** [comment]
@huanghaibin-dev 
奇怪, 我发出邀请上面写在等待验证
可不可以麻烦你加我试试看 3367657152

**Comment by ohpoloha** [comment]
感激不尽! 修好了, 所以关掉这裡
